valor = int(input('Informe um valor inteiro: '))

print(f'0 x {valor} = {0 * valor}')
print(f'1 x {valor} = {1 * valor}')
print(f'2 x {valor} = {2 * valor}')
print(f'3 x {valor} = {3 * valor}')
print(f'4 x {valor} = {4 * valor}')
print(f'5 x {valor} = {5 * valor}')
print(f'6 x {valor} = {6 * valor}')
print(f'7 x {valor} = {7 * valor}')
print(f'8 x {valor} = {8 * valor}')
print(f'9 x {valor} = {9 * valor}')
